(TOP (S (NP (PRP "He"))
        (VP (VBD "was")
            (VP (VBN "named")
                (NP (NP (JJ "chief")
                        (NN "executive")
                        (NN "officer"))
                    (PP (IN "of")
                        (NP (NP (NNP "Applied"))
                            (PP (IN "in")
                                (NP (CD "1986"))))))))
        (|.| ".")))
(TOP (S (NP (PRP "He"))
                    (VP (VBD "was")
                        (VP (VBN "named")
                            (NP (NP (JJ "chief")
                                    (NN "executive")
                                    (NN "officer"))
                                (PP (IN "of")
                                    (NP (NNP "Applied"))))
                            (PP (IN "in")
                                (NP (CD "1986")))))
                    (|.| ".")))


(TOP (S (NP (NNP "Fidelity") (NNPS "Investments"))
        (VP (VP (VBD "placed")
                (NP (JJ "new") (NNS "ads"))
                (PP (IN "in") (NP (NNS "newspapers")))
                (NP (NN "yesterday")))
            (|,| ",")
            (CC "and")
            (VP (VBD "wrote")
                (NP (NP (DT "another") (JJ "new") (NN "ad"))
                    (VBG "appearing"))
                (NP (NN "today"))))
        (|.| ".")))
(TOP (S (NP (NNP "Fidelity") (NNPS "Investments"))
        (VP (VP (VBD "placed")
                (NP (JJ "new") (NNS "ads"))
                (PP (IN "in") (NP (NNS "newspapers")))
                (NP (NN "yesterday")))
            (|,| ",")
            (CC "and")
            (VP (VBD "wrote")
                (NP (NP (DT "another") (JJ "new") (NN "ad"))
                    (VP (VBG "appearing") (NP (NN "today"))))))
        (|.| ".")))


(TOP (S (S (NP (PRP "You"))
           (VP (VBD "did")
               (NP (NP (NN "something"))
                   (ADJP (RB "so") (RB "utterly") (JJ "stupid")))))
        (|,| ",")
        (S (NP (PRP "you"))
           (VP (VBD "had")
               (S (VP (TO "to")
                      (VP (VB "think")
                          (PP (IN "about") (NP (PRP "it"))))))
                (ADVP (RB "ahead")
                      (PP (IN "of") (NP (NN "time"))))))
        (|.| ".")))
(TOP (S (S (NP (PRP "You"))
           (VP (VBD "did")
               (NP (NP (NN "something"))
                   (ADJP (RB "so") (RB "utterly") (JJ "stupid")))))
        (|,| ",")
        (S (NP (PRP "you"))
           (VP (VBD "had")
               (S (VP (TO "to")
                      (VP (VB "think")
                          (PP (IN "about") (NP (PRP "it")))
                          (ADVP (RB "ahead")
                                (PP (IN "of") (NP (NN "time")))))))))
        (|.| ".")))


(TOP (S (NP (DT "The") (NN "bill"))
        (VP (VBZ "intends")
            (S (VP (TO "to")
                   (VP (VB "restrict")
                       (NP (DT "the") (NNP "RTC"))
                       (PP (TO "to")
                           (NP (NNP "Treasury") (NNS "borrowings")))
                       (ADVP (RB "only"))
                       (SBAR (IN "unless")
                             (S (NP (DT "the") (NN "agency"))
                                (VP (VBZ "receives")
                                    (NP
                                     (JJ "specific")
                                     (JJ "congressional")
                                     (NN "authorization")))))))))
        (|.| ".")))
(TOP (S (NP (DT "The") (NN "bill"))
        (VP (VBZ "intends")
            (S (VP (TO "to")
                   (VP (VB "restrict")
                       (NP (DT "the") (NNP "RTC"))
                       (PP (TO "to")
                           (NP (NNP "Treasury") (NNS "borrowings")))
                       (ADVP (RB "only")))))
            (SBAR (IN "unless")
                  (S (NP (DT "the") (NN "agency"))
                     (VP (VBZ "receives")
                         (NP
                            (JJ "specific")
                            (JJ "congressional")
                            (NN "authorization"))))))
        (|.| ".")))


(TOP (S (NP (PRP "He"))
        (VP (VP (VBZ "'s")
                (ADVP (RB "never"))
                (VP (VBD "chuckled") (|,| ",") (CC "or") (VBD "giggled")))
            (|,| ",")
            (CC "or")
            (VP (ADVP (RB "even")) (VBD "smiled")))
        (|.| ".")))
(TOP (S (NP (PRP "He"))
        (VP (VBZ "'s")
            (ADVP (RB "never"))
            (VP (VP (VBD "chuckled"))
                (|,| ",")
                (CC "or")
                (VP (VBD "giggled"))
                (|,| ",")
                (CC "or")
                (VP (ADVP (RB "even")) (VBD "smiled"))))
        (|.| ".")))


(TOP (S (NP (NP (DT "A") (ADJP (CD "16.3") (NN "%")) (NN "drop"))
            (PP (IN "for")
                (NP (NP (NNP "Mannesmann") (NNP "AG"))
                    (CC "and")
                    (NP (NP (NNP "Dresdner")
                            (NNP "Bank")
                            (NNP "AG")
                            (POS "'s"))
                        (ADJP (CD "9.6") (NN "%"))
                        (NN "decline")))))
        (VP (VBD "were")
            (ADJP (RB "especially") (JJ "problematic"))
            (PP (IN "for")
                (NP (NP (PRP$ "their") (JJ "respective") (NNS "boards")))))
        (|.| ".")))
(TOP (S (NP (NP (NP (DT "A") (ADJP (CD "16.3") (NN "%")) (NN "drop"))
                (PP (IN "for")
                    (NP (NNP "Mannesmann") (NNP "AG"))))
            (CC "and")
            (NP (NP (NNP "Dresdner")
                    (NNP "Bank")
                    (NNP "AG")
                    (POS "'s"))
                (ADJP (CD "9.6") (NN "%"))
                (NN "decline")))
        (VP (VBD "were")
            (ADJP (RB "especially") (JJ "problematic"))
            (PP (IN "for")
                (NP (NP (PRP$ "their") (JJ "respective") (NNS "boards")))))
        (|.| ".")))


(TOP (S (NP (NP (NNP "Secretary"))
            (PP (IN "of") (NP (NNP "State") (NNP "Baker"))))
        (PP (IN "in")
            (NP (DT "a") (JJ "foreign") (NN "policy") (NN "speech")))
        (VP (VBD "spoke")
            (PP (IN "about")
                (NP (NP (DT "the") (NN "reunification"))
                    (PP (IN "of") (NP (NNP "Germany"))))))
        (|.| ".")))
(TOP (S (NP (NAC (NNP "Secretary") (PP (IN "of") (NP (NNP "State"))))
            (NNP "Baker"))
        (PP (IN "in")
            (NP (DT "a") (JJ "foreign") (NN "policy") (NN "speech")))
        (VP (VBD "spoke")
            (PP (IN "about")
                (NP (NP (DT "the") (NN "reunification"))
                    (PP (IN "of") (NP (NNP "Germany"))))))
        (|.| ".")))


(TOP (S (SINV (VP (VBG "Following"))
              (VBZ "is")
              (NP (NP (DT "a") (NN "breakdown"))
                  (PP (IN "of")
                      (NP (JJ "major") (NN "market") (NN "activity")))))
        (\: ":")))
(TOP (S (SINV (S (VP (VBG "Following")))
              (VBZ "is")
              (NP (NP (DT "a") (NN "breakdown"))
                  (PP (IN "of")
                      (NP (JJ "major") (NN "market") (NN "activity")))))
        (\: ":")))


(TOP (S (NP (JJ "Young") (NN "man"))
        (|,| ",")
        (VP (VBP "are")
            (NP (NP (PRP "you"))
                (ADJP (JJ "aware")
                      (PP (IN "of")
                          (SBAR (WHNP (WP "what"))
                                (S (NP (PRP "you"))
                                   (VP
                                    (VB "eat")
                                    (CC "and")
                                    (VB "drink"))))))))
        (|.| "?")))
(TOP (SQ (NP (JJ "Young") (NN "man"))
         (|,| ",")
         (VP (VBP "are")
             (NP (NP (PRP "you"))
                 (ADJP (JJ "aware")
                       (PP (IN "of")
                           (SBAR (WHNP (WP "what"))
                                 (S (NP (PRP "you"))
                                    (VP
                                     (VB "eat")
                                     (CC "and")
                                     (VB "drink"))))))))
         (|.| "?")))


(TOP (NP (NP (CD "Eight")
             (JJ "hard-nosed")
             (CC "and")
             (JJ "fearless")
             (NNS "litigators"))
         (SBAR (WHNP (WP "who"))
               (S (VP (VBD "spent")
                      (NP (PRP$ "their") (NNS "hours"))
                      (S (VP (VBG "chewing")
                             (PP (IN "up") (NP (NNS "people"))))))))
         (|.| ".")))
(TOP (NP (NP (CD "Eight")
             (JJ "hard-nosed")
             (CC "and")
             (JJ "fearless")
             (NNS "litigators"))
         (SBAR (WHNP (WP "who"))
               (S (VP (VBD "spent")
                      (NP (PRP$ "their") (NNS "hours"))
                      (S (VP (VBG "chewing")
                             (PRT (RP "up"))
                             (NP (NNS "people")))))))
         (|.| ".")))


(TOP (S (PP (IN "Unlike")
            (NP (JJ "other")
                (NNS "prices")
                (NN "interest")
                (NNS "rates")))
        (VP (VBP "are")
            (S (VP (TO "to")
                   (VP (VB "be")
                       (ADVP (RB "politically"))
                       (VP (VBN "determined"))))))
        (|.| ".")))
(TOP (S (PP (IN "Unlike") (NP (JJ "other") (NNS "prices")))
        (NP (NN "interest") (NNS "rates"))
        (VP (VBP "are")
            (S (VP (TO "to")
                   (VP (VB "be")
                       (ADVP (RB "politically"))
                       (VP (VBN "determined"))))))
        (|.| ".")))
